version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbadmin
      MONGO_INITDB_ROOT_PASSWORD: dbadmin
